spring:
  datasource:
    url: jdbc:postgresql://kotlin-security-service.backend.svc.cluster.local:5432/account?useSSL=false
    username: postgres
    password: Huisheng2021
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000

server:
  port: 10001