spring.profiles.active: @env@

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

jwt:
  token: huisheng-jwt
security:
  jwt:
    secretKey: huisheng-secretKey

