spring:
  datasource:
    url: jdbc:postgresql://rancher.huishengedu.cn:15432/account?useSSL=false
    username: postgres
    password: Huisheng2021
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000

server:
  port: 8080